之前只支持定义回调函数来表明异步操作完成，需要串联多个异步操作，通常需要深度嵌套回调函数（回调地狱），为了解决这个问题，出现了Promise（期约）

# promise

**特点：**

1. 不受外界影响（三种状态）
2. 一旦状态改变，就不会再变（单向）



它可以通过new操作符来实例化

他有三个状态：待定pending，解决resolved，拒绝rejected

通过Promise.resolve()可以实例化一个解决的期约

而通过Promise.reject()会实例化一个拒绝的期约并抛出一个错误，这个错误不能通过try/catch捕捉到，只能通过拒绝处理程序捕获

```js
async function a() {
    try{
        await Promise.reject(new Error('1'))
    } catch(e) {
        console.log(e)
    }
} a()
// Error: 1
//    at a (<anonymous>:3:30)
//    at <anonymous>:5:3
```

必须通过异步模式捕获错误

期约是同步对象（在同步执行模式中使用），但他也是异步执行模式的媒介

因为错误并没有跑到执行**同步**代码的线程里，而是通过浏览器**异步**消息队列来处理的，所以单纯的try/catch不能捕获该错误

## then()

接收两个参数：onResolved和onReject

## catch()

语法糖，相当于then（null，onReject）

## finally()

两种状态都会执行，但无法得知当前处于哪种状态

## all()

传入promise对象数组，全部解决后，才返回

只要有一个拒绝，所有拒绝

## race()

与all类似，不过他的状态取决于第一个落定的状态



# 异步函数

async让函数具有异步特性，但其代码任然是同步求值的

但如果使用了return返回了值，这个值会被Promise.resolve()包装成一个期约对象（没有return返回undefined）

使用await可以暂停异步函数的执行，等待期约解决



先正常执行同步函数，遇见await等异步操作时暂停，向消息队列添加任务

继续后面的同步操作，同步操作完毕后

处理消息队列的操作，遇见异步操作暂停，重新插入消息队列

# 手写async

```js
function async() {
  const args = [].slice.call(arguments)

  function spawn (genF) {
    return new Promise(((resolve, reject) => {
      let gen

      try {
        gen = genF()
      } catch (e) {
        return reject(e)
      }
      //await所接住的值，是promise的resolve的值
      function step(nextF) {
        //next.value是一个promise的值
        const next = nextF()

        if (next.done) {
          //最后的这个东西可以接收到generator函数的return值
          //没有return就是undefined          
          return resolve(next.value)
        }
        //Promise.resolve(next.value)这句话很关键，因为你不知道yield后面的表达式返回什么
        //那么你必须把这个值转为promise，这个是async函数的规定，每个await都是promise,注意这个next.value是promise对象
        Promise.resolve(next.value).then((res) => {
          step(function () {
            return gen.next(res)
          })
        }, (err) => {
          //到下轮next抛出异常，结束执行
          step(function () {
            return gen.throw(err)
          })
        })
      }

      step(function () {
        return gen.next(undefined)
      })
    }))
  }

  return spawn
}
```



# 手写promise

## 树干的

```js
let noop = function () { }; // 空函数
let then = Promise.resolve();
let nextTick = (fn) => {
    then.then(fn); // 将 fn 放到微任务队列里执行
}

// 定义 handler 类
class Handler {
    constructor(promise, onFullfilled, onRejected) {
        this.promise = promise;
        this.onFullfilled = onFullfilled;
        this.onRejected = onRejected;
    }
}

// 定义 myPromise 类
class myPromise {
    constructor(fn) {
        this.value = null; // 值
        this.state = 0; // 状态
        this.deffers = []; // 存储回调函数
        let resolve = (vl) => {
            this._resolve(this, vl);
        }
        let reject = (res) => {
            this._reject(this, res);
        }
        try {
            fn(resolve, reject); // 执行异步函数
        } catch (err) {
            this._reject(this, err)
        }
    }
    then(onFullfilled, onRejected) {
        let res = new myPromise(noop);
        this.handle(this, new Handler(res, onFullfilled, onRejected));
        return res;
    }
    catch(onRejected) {
        return this.then(null, onRejected);
    }
    static resolve(vl) {
        return new myPromise((resolve) => resolve(vl));
    }
    // 处理回调函数
    handle(p, deffer) {
        while (p.state == 3) {
            p = p.value;
        }
        if (p.state == 0) {
            p.deffers.push(deffer);
            return;
        }
        let cb = p.state == 1 ? deffer.onFullfilled : deffer.onRejected;
        if (cb == null) {
            // 没有指定回调
            if (p.state == 1) {
                this._resolve(deffer.promise, p.value);
            } else {
                this._reject(deffer.promise, p.value);
            }
            return;
        }
        // 有指定回调
        try {
            let ret = cb(p.value);
            this._resolve(deffer.promise, ret);
        } catch (err) {
            this._reject(deffer.promise, err);
        }
    }
    // resolve 功能函数
    _resolve(p, vl) {
        if (vl instanceof myPromise) {
            p.state = 3;
        } else {
            p.state = 1;
        }
        p.value = vl;
        nextTick(() => {
            for (let deffer of p.deffers) {
                this.handle(p, deffer);
            }
            p.deffers = [];
        })
    }
    // reject 功能函数
    _reject(p, res) {
        p.state = 2;
        p.value = res;
        if (p.deffers.length == 0) {
            // p.deffers.length 为 0，说明 p 后面没有 then 了，这个错误直接扔出
            throw res;
        }
        nextTick(() => {
            for (let deffer of p.deffers) {
                this.handle(p, deffer);
            }
            p.deffers = [];
        })
    }
}

// 测试用例
let a = new myPromise((resolve, reject) => {
    setTimeout(() => {
        resolve(99);
    }, 1000)
})
a.then(res => console.log('回调1'));
a.then(res => console.log('回调2'));
a.then(res => console.log('回调3'));
a.then(res => console.log('回调4'));
a.then(res => console.log('回调5'));

let b = a.then(res => res + 1)
    .then(res => {
        console.log(res);
        throw Error(1);
    })
    .catch(err => myPromise.resolve(myPromise.resolve(myPromise.resolve(err))))
    .then(res => console.log(res))
    .then(res => console.log(a, b));
```

## 圣源的

```js
class MyPromise {
  constructor(fn) {
    const resolve = (value) => {
      this.status = 'resolved'
      this.resolvedValue = value

      while (this.queueFunction.length) {
        const fn = this.queueFunction.shift()
        fn(this.resolvedValue)
      }
    }

    const reject = (value) => {
      this.status = 'rejected'
      this.rejectedValue = value

      while (this.rejectedQueue.length) {
        const fn = this.rejectedQueue.shift()
        fn(this.resolvedValue)
      }
    }

    this.status = 'pending'
    this.queueFunction = []
    this.rejectedQueue = []

    fn(resolve, reject)
  }

  then(thenable) {
    function exec(value, thenable, resolve, reject) {
      const result = thenable(value)

      if (result instanceof MyPromise) {
        result.then(d => {
          resolve(d)
        })
      } else {
        resolve(result)
      }
    }

    return new MyPromise((resolve, reject) => {
      if (this.status === 'resolved') {
        exec(this.resolvedValue, thenable, resolve, reject)
      } else {
        this.queueFunction.push((value) => {
          exec(value, thenable, resolve, reject)
        })
      }
    })
  }

  catch (thenable) {

  }

  static resolve() {

  }

  static all (arr) {
    return new MyPromise((resolve, reject) => {
      let fulfill_num = 0
      const resArr = []
      for (let i = 0; i < arr.length; i++) {
        arr[i].then(res => {
          fulfill_num++
          resArr[i] = res

          if (fulfill_num === arr.length) {
            resolve(resArr)
          }
        }).catch(res => {
          reject(res)
        })
      }
    })
  }

  static race(arr) {
    return new MyPromise((resolve, reject) => {
      for (let i = 0; i < arr.length; i++) {
        arr[i].then(res => {
          resolve(res)
        }).catch(res => {
          reject(res)
        })
      }
    })
  }

}
```



## 桂佳的

```js
/**
 * Promise 实现 遵循promise/A+规范
 * Promise/A+规范译文:
 * https://malcolmyu.github.io/2015/06/12/Promises-A-Plus/#note-4
 */

// promise 三个状态
const PENDING = "pending";
const FULFILLED = "fulfilled";
const REJECTED = "rejected";

function Promise(excutor) {
    let that = this; // 缓存当前promise实例对象
    that.status = PENDING; // 初始状态
    that.value = undefined; // fulfilled状态时 返回的信息
    that.reason = undefined; // rejected状态时 拒绝的原因
    that.onFulfilledCallbacks = []; // 存储fulfilled状态对应的onFulfilled函数
    that.onRejectedCallbacks = []; // 存储rejected状态对应的onRejected函数

    function resolve(value) { // value成功态时接收的终值
        if (value instanceof Promise) {
            return value.then(resolve, reject);
        }

        // 为什么resolve 加setTimeout?
        // 2.2.4规范 onFulfilled 和 onRejected 只允许在 execution context 栈仅包含平台代码时运行.
        // 注1 这里的平台代码指的是引擎、环境以及 promise 的实施代码。实践中要确保 onFulfilled 和 onRejected 方法异步执行，且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。

        setTimeout(() => {
            // 调用resolve 回调对应onFulfilled函数
            if (that.status === PENDING) {
                // 只能由pedning状态 => fulfilled状态 (避免调用多次resolve reject)
                that.status = FULFILLED;
                that.value = value;
                that.onFulfilledCallbacks.forEach(cb => cb(that.value));
            }
        });
    }

    function reject(reason) { // reason失败态时接收的拒因
        setTimeout(() => {
            // 调用reject 回调对应onRejected函数
            if (that.status === PENDING) {
                // 只能由pedning状态 => rejected状态 (避免调用多次resolve reject)
                that.status = REJECTED;
                that.reason = reason;
                that.onRejectedCallbacks.forEach(cb => cb(that.reason));
            }
        });
    }

    // 捕获在excutor执行器中抛出的异常
    // new Promise((resolve, reject) => {
    //     throw new Error('error in excutor')
    // })
    try {
        excutor(resolve, reject);
    } catch (e) {
        reject(e);
    }
}

/**
 * resolve中的值几种情况：
 * 1.普通值
 * 2.promise对象
 * 3.thenable对象/函数
 */

/**
 * 对resolve 进行改造增强 针对resolve中不同值情况 进行处理
 * @param  {promise} promise2 promise1.then方法返回的新的promise对象
 * @param  {[type]} x         promise1中onFulfilled的返回值
 * @param  {[type]} resolve   promise2的resolve方法
 * @param  {[type]} reject    promise2的reject方法
 */
function resolvePromise(promise2, x, resolve, reject) {
    if (promise2 === x) {  // 如果从onFulfilled中返回的x 就是promise2 就会导致循环引用报错
        return reject(new TypeError('循环引用'));
    }

    let called = false; // 避免多次调用
    // 如果x是一个promise对象 （该判断和下面 判断是不是thenable对象重复 所以可有可无）
    if (x instanceof Promise) { // 获得它的终值 继续resolve
        if (x.status === PENDING) { // 如果为等待态需等待直至 x 被执行或拒绝 并解析y值
            x.then(y => {
                resolvePromise(promise2, y, resolve, reject);
            }, reason => {
                reject(reason);
            });
        } else { // 如果 x 已经处于执行态/拒绝态(值已经被解析为普通值)，用相同的值执行传递下去 promise
            x.then(resolve, reject);
        }
        // 如果 x 为对象或者函数
    } else if (x != null && ((typeof x === 'object') || (typeof x === 'function'))) {
        try { // 是否是thenable对象（具有then方法的对象/函数）
            let then = x.then;
            if (typeof then === 'function') {
                then.call(x, y => {
                    if (called) return;
                    called = true;
                    resolvePromise(promise2, y, resolve, reject);
                }, reason => {
                    if (called) return;
                    called = true;
                    reject(reason);
                })
            } else { // 说明是一个普通对象/函数
                resolve(x);
            }
        } catch (e) {
            if (called) return;
            called = true;
            reject(e);
        }
    } else {
        resolve(x);
    }
}

/**
 * [注册fulfilled状态/rejected状态对应的回调函数]
 * @param  {function} onFulfilled fulfilled状态时 执行的函数
 * @param  {function} onRejected  rejected状态时 执行的函数
 * @return {function} newPromsie  返回一个新的promise对象
 */
Promise.prototype.then = function (onFulfilled, onRejected) {
    const that = this;
    let newPromise;
    // 处理参数默认值 保证参数后续能够继续执行
    onFulfilled =
        typeof onFulfilled === "function" ? onFulfilled : value => value;
    onRejected =
        typeof onRejected === "function" ? onRejected : reason => {
            throw reason;
        };

    // then里面的FULFILLED/REJECTED状态时 为什么要加setTimeout ?
    // 原因:
    // 其一 2.2.4规范 要确保 onFulfilled 和 onRejected 方法异步执行(且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行) 所以要在resolve里加上setTimeout
    // 其二 2.2.6规范 对于一个promise，它的then方法可以调用多次.（当在其他程序中多次调用同一个promise的then时 由于之前状态已经为FULFILLED/REJECTED状态，则会走的下面逻辑),所以要确保为FULFILLED/REJECTED状态后 也要异步执行onFulfilled/onRejected

    // 其二 2.2.6规范 也是resolve函数里加setTimeout的原因
    // 总之都是 让then方法异步执行 也就是确保onFulfilled/onRejected异步执行

    // 如下面这种情景 多次调用p1.then
    // p1.then((value) => { // 此时p1.status 由pedding状态 => fulfilled状态
    //     console.log(value); // resolve
    //     // console.log(p1.status); // fulfilled
    //     p1.then(value => { // 再次p1.then 这时已经为fulfilled状态 走的是fulfilled状态判断里的逻辑 所以我们也要确保判断里面onFuilled异步执行
    //         console.log(value); // 'resolve'
    //     });
    //     console.log('当前执行栈中同步代码');
    // })
    // console.log('全局执行栈中同步代码');
    //

    if (that.status === FULFILLED) { // 成功态
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onFulfilled(that.value);
                    resolvePromise(newPromise, x, resolve, reject); // 新的promise resolve 上一个onFulfilled的返回值
                } catch (e) {
                    reject(e); // 捕获前面onFulfilled中抛出的异常 then(onFulfilled, onRejected);
                }
            });
        })
    }

    if (that.status === REJECTED) { // 失败态
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onRejected(that.reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        });
    }

    if (that.status === PENDING) { // 等待态
        // 当异步调用resolve/rejected时 将onFulfilled/onRejected收集暂存到集合中
        return newPromise = new Promise((resolve, reject) => {
            that.onFulfilledCallbacks.push((value) => {
                try {
                    let x = onFulfilled(value);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
            that.onRejectedCallbacks.push((reason) => {
                try {
                    let x = onRejected(reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        });
    }
};

/**
 * Promise.all Promise进行并行处理
 * 参数: promise对象组成的数组作为参数
 * 返回值: 返回一个Promise实例
 * 当这个数组里的所有promise对象全部变为resolve状态的时候，才会resolve。
 */
Promise.all = function (promises) {
    return new Promise((resolve, reject) => {
        let done = gen(promises.length, resolve);
        promises.forEach((promise, index) => {
            promise.then((value) => {
                done(index, value)
            }, reject)
        })
    })
}

function gen(length, resolve) {
    let count = 0;
    let values = [];
    return function (i, value) {
        values[i] = value;
        if (++count === length) {
            console.log(values);
            resolve(values);
        }
    }
}

/**
 * Promise.race
 * 参数: 接收 promise对象组成的数组作为参数
 * 返回值: 返回一个Promise实例
 * 只要有一个promise对象进入 FulFilled 或者 Rejected 状态的话，就会继续进行后面的处理(取决于哪一个更快)
 */
Promise.race = function (promises) {
    return new Promise((resolve, reject) => {
        promises.forEach((promise, index) => {
            promise.then(resolve, reject);
        });
    });
}

// 用于promise方法链时 捕获前面onFulfilled/onRejected抛出的异常
Promise.prototype.catch = function (onRejected) {
    return this.then(null, onRejected);
}

Promise.resolve = function (value) {
    return new Promise(resolve => {
        resolve(value);
    });
}

Promise.reject = function (reason) {
    return new Promise((resolve, reject) => {
        reject(reason);
    });
}

/**
 * 基于Promise实现Deferred的
 * Deferred和Promise的关系
 * - Deferred 拥有 Promise
 * - Deferred 具备对 Promise的状态进行操作的特权方法（resolve reject）
 *
 *参考jQuery.Deferred
 *url: http://api.jquery.com/category/deferred-object/
 */
Promise.deferred = function () { // 延迟对象
    let defer = {};
    defer.promise = new Promise((resolve, reject) => {
        defer.resolve = resolve;
        defer.reject = reject;
    });
    return defer;
}

module.exports = Promise
```

## 简化版

只有resolve，reject，then，catch

```js
function Promise(fn) {
    let that = this;
    that.state = 0; // 0-pending，1-fulfilled, 2-rejected
    that.value = undefined;
    that.reason = undefined;
    that.onFulfulledCallbacks = [];
    that.onRejectedCallbacks = [];

    function resolve(val) {
        // 返回另一个promise对象
        if (val instanceof Promise) {
            return value.then(resolve, reject);
        }
        // 返回的是一个值
        setTimeout(() => {
            if (that.state === 0) {
                that.state = 1;
                that.value = val;
                that.onFulfulledCallbacks.forEach(cb => cb(that.value))
            }
        })
    }
    function reject(reason) {
        setTimeout(() => {
            if (that.state === 0) {
                that.state = 2;
                that.reason = reason;
                that.onRejectedCallbacks.forEach(cb => cb(that.value))
            }
        });
    }

    try {
        fn(resolve, reject)
    } catch (error) {
        reject(error)
    }
}

Promise.prototype.then = function (onResolve, onReject) {
    const that = this;
    let newPromise;
    // 处理参数默认值
    onResolve = typeof onResolve === 'function' ? onResolve : value => value;
    onReject = typeof onReject === 'function' ? onReject : reason => { throw reason };

    if (that.state === 1) {
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onResolve(that.value);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (error) {
                    reject(error)
                }
            });
        })
    }

    if (that.state === 2) {
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onReject(that.reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (error) {
                    reject(error)
                }
            });
        })
    }

    if (that.state === 0) {
        return newPromise = new Promise((resolve, reject) => {
            that.onFulfulledCallbacks.push((value) => {
                try {
                    let x = onResolve(value);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (error) {
                    reject(error)
                }
            });
            that.onRejectedCallbacks.push((reason) => {
                try {
                    let x = onReject(reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch (error) {
                    reject(error)
                }
            })
        })
    }
}

Promise.prototype.catch = function (onReject) {
    this.then(null, onReject)
}

function resolvePromise(p, x, resolve, reject) {
    console.log('resolvePromise', p, x)
    if (p === x) {
        return reject(new TypeError('循环引用'))
    }

    let called = false;// 避免多次调用

    if (x instanceof Promise) {// then中返回的值是promise对象
        if (x.state === 0) {
            x.then(y => {
                resolvePromise(p2, y, resolve, reject)
            }, reason => {
                reject(reason);
            })
        } else {
            x.then(resolve, reject)
        }
    } else if (x != null && ((typeof x === 'object') || (typeof x === 'function'))) {
        try {// 有then方法的对象/函数
            let then = x.then;
            if (typeof then === 'function') {
                then.call(x, y => {
                    if (called) return;
                    called = true;
                    resolvePromise(p, y, resolve, reject)
                }, reason => {
                    if (called) return;
                    called = true;
                    reject(reason)
                })
            } else { // 普通对象/函数
                resolve(x)
            }
        } catch (e) {
            if (called) return;
            called = true;
            reject(e)
        }
    } else {
        resolve(x)
    }
}


// 测试用例
let a = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(99);
    }, 1000)
})
a.then(res => console.log('回调1'));
a.then(res => console.log('回调2'));
a.then(res => console.log('回调3'));
a.then(res => console.log('回调4'));
a.then(res => console.log('回调5'));

let b = a.then(res => res + 1)
    .then(res => {
        console.log(res);
        throw Error(1);
    })
    .catch(err => Promise.resolve(Promise.resolve(Promise.resolve(err))))
let c = a.then(res => console.log(res))
    .then(res => console.log(a, b));
```

